application: oogositecode
version: 1
runtime: go
api_version: 2

handlers:
- url: /images
  static_dir: images
- url: /.*
  script: _go_app
- url: /favicon.ico
  static_files: /favicon.ico
  upload: /favicon.ico
  